export type ProductReview = { text: string };
export type Product = {
  id: string;
  name: string;
  category: string;
  price: number;
  styleTags: string[];
  colorTags: string[];
  roomTags: string[];
  constraints: string[];
  description: string;
  embeddingText: string;
  imageUrl: string;
  bg: string;
  // extended detail
  brand?: string;
  material?: string;
  sizes?: string[];
  colorsAvailable?: string[];
  deliveryDays?: number;
  discountPct?: number;
  rating?: number;
  reviewCount?: number;
  reviews?: { positive: string[]; critical: string[] };
};

export const PRODUCTS: Product[] = [
  { id: "lamp_001", name: "Warm Glow Floor Lamp", category: "Lighting", price: 2499, styleTags: ["warm","cozy","modern","minimalist"], colorTags: ["beige","wood","cream"], roomTags: ["living room","bedroom","reading corner"], constraints: ["renter-friendly","no-drill","small-space"], description: "Slim floor lamp with warm light, ideal for cozy corners without wall installation.", embeddingText: "warm cozy floor lamp renter friendly no drill small space reading corner soft lighting ambient", imageUrl: "https://images.pexels.com/photos/31149584/pexels-photo-31149584.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#f3e3cf" },
  { id: "lamp_002", name: "Paper Globe Pendant (Plug-in)", category: "Lighting", price: 1799, styleTags: ["boho","warm","minimalist"], colorTags: ["cream","white"], roomTags: ["bedroom","living room"], constraints: ["renter-friendly","no-drill","plug-in"], description: "Plug-in paper globe with diffused warm glow. No hardwiring needed.", embeddingText: "paper globe pendant plug in warm boho diffused soft warm light renter", imageUrl: "https://images.pexels.com/photos/19314176/pexels-photo-19314176.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#f6ead9" },
  { id: "lamp_003", name: "Clip-On Reading Light", category: "Lighting", price: 899, styleTags: ["modern","minimalist"], colorTags: ["black","brass"], roomTags: ["reading corner","bedroom","study"], constraints: ["renter-friendly","no-drill","small-space"], description: "Adjustable clip-on for headboards or shelves. Perfect task light for reading.", embeddingText: "clip on reading light task small space renter focused warm bulb", imageUrl: "https://images.pexels.com/photos/35329516/pexels-photo-35329516.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#ede4d3" },
  { id: "lamp_004", name: "Fairy String Lights (Battery)", category: "Lighting", price: 499, styleTags: ["boho","cozy","warm","romantic"], colorTags: ["gold","warm"], roomTags: ["bedroom","balcony","reading corner","living room"], constraints: ["renter-friendly","no-drill","battery","low-maintenance"], description: "Battery-powered warm white fairy lights to drape anywhere.", embeddingText: "fairy string lights battery warm cozy boho drape no drill ambient", imageUrl: "https://images.pexels.com/photos/35418899/pexels-photo-35418899.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#f5e9c9" },
  { id: "lamp_005", name: "Himalayan Salt Lamp", category: "Lighting", price: 1299, styleTags: ["earthy","warm","calm"], colorTags: ["amber","pink"], roomTags: ["bedroom","reading corner","living room"], constraints: ["renter-friendly","no-drill","small-space"], description: "Soft amber glow with a grounded, earthy feel.", embeddingText: "himalayan salt lamp earthy warm calm ambient bedside", imageUrl: "https://images.pexels.com/photos/5911961/pexels-photo-5911961.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#f4d5b8" },

  { id: "rug_001", name: "Jute Round Rug 4ft", category: "Rugs", price: 1899, styleTags: ["boho","earthy","warm","natural"], colorTags: ["beige","brown"], roomTags: ["reading corner","living room","bedroom"], constraints: ["renter-friendly","small-space","low-maintenance"], description: "Hand-woven jute rug that anchors a cozy corner.", embeddingText: "jute round rug natural boho earthy warm corner anchor small", imageUrl: "https://images.pexels.com/photos/17033989/pexels-photo-17033989.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#e6d2b3" },
  { id: "rug_002", name: "Tufted Cotton Rug 3x5", category: "Rugs", price: 2299, styleTags: ["modern","minimalist","calm"], colorTags: ["cream","grey"], roomTags: ["living room","bedroom"], constraints: ["renter-friendly","washable","low-maintenance"], description: "Soft tufted cotton rug, machine washable.", embeddingText: "tufted cotton rug washable modern minimalist soft cream", imageUrl: "https://images.pexels.com/photos/9428154/pexels-photo-9428154.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#ece4d6" },
  { id: "rug_003", name: "Kilim Runner", category: "Rugs", price: 1599, styleTags: ["boho","colorful","earthy"], colorTags: ["rust","terracotta","navy"], roomTags: ["entryway","bedroom","living room"], constraints: ["renter-friendly","small-space"], description: "Vibrant flat-weave runner with bohemian patterns.", embeddingText: "kilim runner boho colorful flatweave entryway pattern terracotta", imageUrl: "https://images.pexels.com/photos/34131689/pexels-photo-34131689.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#e8c9a8" },
  { id: "rug_004", name: "Faux Sheepskin Throw Rug", category: "Rugs", price: 999, styleTags: ["cozy","warm","scandi"], colorTags: ["cream","white"], roomTags: ["reading corner","bedroom"], constraints: ["renter-friendly","small-space"], description: "Plush sheepskin to layer on chairs or floor for warmth.", embeddingText: "faux sheepskin throw rug cozy warm scandi layer chair reading", imageUrl: "https://images.pexels.com/photos/18281425/pexels-photo-18281425.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#f4ecdd" },

  { id: "cush_001", name: "Linen Cushion Set of 2", category: "Cushions", price: 1099, styleTags: ["warm","cozy","minimalist","modern"], colorTags: ["beige","ochre"], roomTags: ["living room","bedroom","reading corner"], constraints: ["renter-friendly","low-maintenance"], description: "Soft linen covers in warm neutrals — the perfect cozy layer.", embeddingText: "linen cushion set warm neutral ochre cozy living bedroom layer", imageUrl: "https://images.pexels.com/photos/24304750/pexels-photo-24304750.png?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#ecd9b8" },
  { id: "cush_002", name: "Velvet Lumbar Pillow", category: "Cushions", price: 799, styleTags: ["luxe","warm","romantic"], colorTags: ["rust","terracotta"], roomTags: ["reading corner","bedroom","living room"], constraints: ["renter-friendly"], description: "Rust velvet lumbar pillow that adds a pop of warmth.", embeddingText: "velvet lumbar pillow rust terracotta warm luxe accent", imageUrl: "https://images.pexels.com/photos/8634414/pexels-photo-8634414.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#e7b89a" },
  { id: "cush_003", name: "Boho Tassel Cushion", category: "Cushions", price: 699, styleTags: ["boho","colorful","earthy"], colorTags: ["cream","brown"], roomTags: ["living room","reading corner"], constraints: ["renter-friendly"], description: "Cotton cushion with hand-knotted tassels.", embeddingText: "boho tassel cushion cream brown hand knotted reading", imageUrl: "https://images.pexels.com/photos/35431235/pexels-photo-35431235.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#eedfc4" },
  { id: "cush_004", name: "Floor Cushion XL", category: "Cushions", price: 1499, styleTags: ["boho","cozy","earthy"], colorTags: ["mustard","brown"], roomTags: ["reading corner","living room","balcony"], constraints: ["renter-friendly","small-space","floor-based"], description: "Oversized floor cushion that doubles as casual seating.", embeddingText: "floor cushion oversized seating boho small space reading nook", imageUrl: "https://images.pexels.com/photos/24304750/pexels-photo-24304750.png?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#e9c98c" },

  { id: "thr_001", name: "Chunky Knit Throw", category: "Throws", price: 1299, styleTags: ["cozy","warm","scandi"], colorTags: ["cream","beige"], roomTags: ["reading corner","bedroom","living room"], constraints: ["renter-friendly","low-maintenance"], description: "Heavy chunky-knit throw for snuggling with a book.", embeddingText: "chunky knit throw cozy warm cream scandi blanket reading", imageUrl: "https://images.pexels.com/photos/16805285/pexels-photo-16805285.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#f1e6d0" },
  { id: "thr_002", name: "Mulmul Cotton Throw", category: "Throws", price: 899, styleTags: ["minimalist","calm","natural"], colorTags: ["white","beige"], roomTags: ["bedroom","living room"], constraints: ["renter-friendly","washable","low-maintenance"], description: "Light breathable cotton throw in soft natural tones.", embeddingText: "mulmul cotton throw breathable natural calm washable", imageUrl: "https://images.pexels.com/photos/16805285/pexels-photo-16805285.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#f4ecdc" },
  { id: "thr_003", name: "Woven Wool Blanket", category: "Throws", price: 1899, styleTags: ["earthy","warm","boho"], colorTags: ["rust","brown"], roomTags: ["reading corner","bedroom","living room"], constraints: ["renter-friendly"], description: "Earthy woven wool blanket with subtle stripes.", embeddingText: "woven wool blanket earthy rust warm stripes boho", imageUrl: "https://images.pexels.com/photos/6462892/pexels-photo-6462892.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#dfb798" },

  { id: "cur_001", name: "Sheer Linen Curtains (Tension Rod)", category: "Curtains", price: 1599, styleTags: ["minimalist","calm","warm"], colorTags: ["cream","white"], roomTags: ["bedroom","living room"], constraints: ["renter-friendly","no-drill","tension-rod"], description: "Light sheer curtains with included tension rod — no drilling.", embeddingText: "sheer linen curtains tension rod no drill renter cream", imageUrl: "https://images.pexels.com/photos/9555225/pexels-photo-9555225.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#f3ecdb" },
  { id: "cur_002", name: "Blackout Curtains with Tension Rod", category: "Curtains", price: 2199, styleTags: ["modern","calm"], colorTags: ["beige","grey"], roomTags: ["bedroom"], constraints: ["renter-friendly","no-drill","tension-rod"], description: "Blackout curtains with tension rod for renters.", embeddingText: "blackout curtains tension rod renter bedroom calm", imageUrl: "https://images.pexels.com/photos/10366653/pexels-photo-10366653.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#e8e0cd" },

  { id: "wall_001", name: "Macramé Wall Hanging (Adhesive Hook)", category: "Wall decor", price: 899, styleTags: ["boho","earthy","cozy"], colorTags: ["cream","beige"], roomTags: ["bedroom","reading corner","living room"], constraints: ["renter-friendly","no-drill","adhesive"], description: "Hand-knotted macramé that hangs from a 3M adhesive hook.", embeddingText: "macrame wall hanging adhesive hook boho earthy renter no drill", imageUrl: "https://images.pexels.com/photos/31352326/pexels-photo-31352326.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#eddcc2" },
  { id: "wall_002", name: "Framed Art Print Trio (Lean)", category: "Wall decor", price: 1499, styleTags: ["modern","minimalist","warm"], colorTags: ["beige","ochre"], roomTags: ["living room","bedroom","reading corner"], constraints: ["renter-friendly","no-drill","lean"], description: "Three lightweight prints meant to lean against the wall on a shelf.", embeddingText: "framed art prints lean shelf no drill warm modern trio", imageUrl: "https://images.pexels.com/photos/11584919/pexels-photo-11584919.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#ecdcc0" },
  { id: "wall_003", name: "Adhesive LED Wall Sconce", category: "Wall decor", price: 1299, styleTags: ["modern","warm"], colorTags: ["brass","gold"], roomTags: ["reading corner","bedroom"], constraints: ["renter-friendly","no-drill","adhesive","battery"], description: "Battery sconce with adhesive backing — no wires, no drilling.", embeddingText: "adhesive led wall sconce battery no drill brass reading", imageUrl: "https://images.pexels.com/photos/30369259/pexels-photo-30369259.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#ecd9b2" },

  { id: "mir_001", name: "Leaning Arched Floor Mirror", category: "Mirrors", price: 3499, styleTags: ["modern","minimalist","warm"], colorTags: ["wood","gold"], roomTags: ["bedroom","living room","entryway"], constraints: ["renter-friendly","no-drill","floor-based"], description: "Full-length arched mirror designed to lean — no installation.", embeddingText: "leaning arched floor mirror full length lean no drill renter", imageUrl: "https://images.pexels.com/photos/8725574/pexels-photo-8725574.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#e6d5b8" },
  { id: "mir_002", name: "Round Tabletop Mirror", category: "Mirrors", price: 799, styleTags: ["modern","minimalist"], colorTags: ["brass"], roomTags: ["bedroom","entryway"], constraints: ["renter-friendly","small-space"], description: "Compact round mirror for vanities and side tables.", embeddingText: "round tabletop mirror brass small space vanity", imageUrl: "https://images.pexels.com/photos/3061279/pexels-photo-3061279.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#ead7b8" },

  { id: "sto_001", name: "Woven Storage Basket", category: "Storage", price: 999, styleTags: ["boho","earthy","cozy","natural"], colorTags: ["beige","brown"], roomTags: ["living room","bedroom","reading corner"], constraints: ["renter-friendly","low-maintenance"], description: "Seagrass basket for blankets, magazines or plants.", embeddingText: "woven storage basket seagrass blankets magazines plants boho natural", imageUrl: "https://images.pexels.com/photos/10557895/pexels-photo-10557895.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#ead2a8" },
  { id: "sto_002", name: "Foldable Fabric Ottoman", category: "Storage", price: 1799, styleTags: ["modern","cozy"], colorTags: ["beige","grey"], roomTags: ["living room","bedroom","reading corner"], constraints: ["renter-friendly","small-space","floor-based"], description: "Storage ottoman that doubles as a footrest.", embeddingText: "foldable fabric ottoman storage footrest small space", imageUrl: "https://images.pexels.com/photos/28321386/pexels-photo-28321386.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#e6dcc7" },

  { id: "shf_001", name: "Leaning Ladder Shelf", category: "Shelves", price: 3299, styleTags: ["modern","minimalist","warm"], colorTags: ["wood"], roomTags: ["living room","bedroom","reading corner"], constraints: ["renter-friendly","no-drill","lean","floor-based"], description: "Wooden ladder shelf that leans — books, plants and decor without drilling.", embeddingText: "leaning ladder shelf wood lean no drill books plants renter", imageUrl: "https://images.pexels.com/photos/2781538/pexels-photo-2781538.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#e7c8a1" },
  { id: "shf_002", name: "Floor Bookstack Stand", category: "Shelves", price: 1499, styleTags: ["modern","minimalist"], colorTags: ["black","wood"], roomTags: ["reading corner","living room"], constraints: ["renter-friendly","no-drill","small-space","floor-based"], description: "Slim floor stand for stacking books beside a chair.", embeddingText: "floor bookstack stand slim small reading no drill", imageUrl: "https://images.pexels.com/photos/20640156/pexels-photo-20640156.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#ecd9b9" },

  { id: "tab_001", name: "Round Mango Wood Side Table", category: "Side tables", price: 2299, styleTags: ["earthy","warm","boho"], colorTags: ["wood","brown"], roomTags: ["reading corner","living room","bedroom"], constraints: ["renter-friendly","small-space","floor-based"], description: "Compact mango wood side table for a mug and a book.", embeddingText: "round mango wood side table small reading mug book warm", imageUrl: "https://images.pexels.com/photos/15480366/pexels-photo-15480366.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#dcb78b" },
  { id: "tab_002", name: "Cane C-Shaped Side Table", category: "Side tables", price: 1899, styleTags: ["modern","boho","minimalist"], colorTags: ["cream","cane"], roomTags: ["reading corner","living room"], constraints: ["renter-friendly","small-space","floor-based"], description: "C-shape slides under sofas and chairs — perfect for tight spaces.", embeddingText: "cane c shape side table slim slides under sofa small reading", imageUrl: "https://images.pexels.com/photos/8725603/pexels-photo-8725603.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#ecdfc4" },

  { id: "pla_001", name: "Snake Plant in Terracotta Pot", category: "Plants", price: 699, styleTags: ["earthy","calm","natural"], colorTags: ["green","terracotta"], roomTags: ["bedroom","living room","reading corner","balcony"], constraints: ["renter-friendly","low-maintenance","small-space"], description: "Hardy snake plant — thrives on neglect.", embeddingText: "snake plant terracotta pot low maintenance hardy bedroom corner", imageUrl: "https://images.pexels.com/photos/3101767/pexels-photo-3101767.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#dbe3c8" },
  { id: "pla_002", name: "Pothos Hanging Planter (Adhesive)", category: "Plants", price: 599, styleTags: ["boho","natural"], colorTags: ["green"], roomTags: ["living room","bedroom","balcony"], constraints: ["renter-friendly","no-drill","adhesive","low-maintenance"], description: "Pothos with adhesive macramé hanger — no drilling.", embeddingText: "pothos hanging planter adhesive macrame no drill renter green", imageUrl: "https://images.pexels.com/photos/12123235/pexels-photo-12123235.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#d9e2c7" },
  { id: "pla_003", name: "Areca Palm Floor Plant", category: "Plants", price: 1299, styleTags: ["natural","calm","boho"], colorTags: ["green"], roomTags: ["living room","balcony","bedroom"], constraints: ["renter-friendly","floor-based","low-maintenance"], description: "Statement floor plant that softens any corner.", embeddingText: "areca palm floor plant statement corner soft natural", imageUrl: "https://images.pexels.com/photos/3012430/pexels-photo-3012430.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#d4ddbe" },

  { id: "dec_001", name: "Soy Wax Candle Set", category: "Decor accents", price: 799, styleTags: ["warm","cozy","calm"], colorTags: ["cream","amber"], roomTags: ["bedroom","living room","reading corner"], constraints: ["renter-friendly","small-space"], description: "Set of three soy candles in warm scents — vanilla, sandalwood, amber.", embeddingText: "soy wax candle set warm cozy vanilla sandalwood amber scent", imageUrl: "https://images.pexels.com/photos/7234498/pexels-photo-7234498.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#f3e5c8" },
  { id: "dec_002", name: "Ceramic Vase Trio", category: "Decor accents", price: 1199, styleTags: ["modern","earthy","minimalist"], colorTags: ["cream","beige"], roomTags: ["living room","bedroom"], constraints: ["renter-friendly","small-space"], description: "Three ceramic vases in tonal cream — clusters beautifully.", embeddingText: "ceramic vase trio tonal cream cluster modern earthy", imageUrl: "https://images.pexels.com/photos/18646117/pexels-photo-18646117.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#ecdcbe" },
  { id: "dec_003", name: "Wooden Incense Holder", category: "Decor accents", price: 349, styleTags: ["earthy","calm","boho"], colorTags: ["wood"], roomTags: ["bedroom","reading corner","living room"], constraints: ["renter-friendly","small-space","low-maintenance"], description: "Hand-carved holder for a slow grounding ritual.", embeddingText: "wooden incense holder hand carved grounding ritual calm", imageUrl: "https://images.pexels.com/photos/24743541/pexels-photo-24743541.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=600&w=600", bg: "#e7caa1" },
];
